//! Integration tests validating Rust inference kernels against high-precision SymPy golden vectors.
//!
//! Ensures that numerical drift during the Mamba recurrence loop and Box-Cox companding
//! remains strictly below perceptual thresholds.

use serde::Deserialize;
use std::fs;
use std::path::PathBuf;
use inference::model::BoxCoxDequantizer;
// Import your InferenceRunner once it is integrated with the new kernels
// use inference::runner::InferenceRunner;

#[derive(Debug, Deserialize)]
struct BoxCoxReference {
    y: f32,
    lambda: f32,
    exact_x: f32,
}

#[derive(Debug, Deserialize)]
struct FoaReference {
    w: f32,
    x: f32,
    y: f32,
    z: f32,
}

#[derive(Debug, Deserialize)]
struct TraceStep {
    step: usize,
    conditioning_sample_sum: f32,
    latent_state_norm: f32,
    top_2_experts: Vec<usize>,
    top_2_weights: Vec<f32>,
    foa: FoaReference,
}

#[derive(Debug, Deserialize)]
struct GoldenVectors {
    description: String,
    latent_dim: usize,
    condition_dim: usize,
    num_experts: usize,
    box_cox_reference: Vec<BoxCoxReference>,
    trace: Vec<TraceStep>,
}

fn load_golden_vectors() -> GoldenVectors {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("data/golden_vectors/baseline_step_trace.json");
    
    let file_content = fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("Failed to read golden vectors at: {:?}", path));
        
    serde_json::from_str(&file_content)
        .expect("Failed to deserialize golden vectors JSON")
}

#[test]
fn test_box_cox_inversion_precision() {
    let golden = load_golden_vectors();
    let epsilon = 1e-4; // Maximum allowed error for single-precision floats

    for ref_point in golden.box_cox_reference {
        // We use the nominal bit width of 8.0 for these companded references as a proxy 
        // to bypass the discrete staircasing and test the pure manifold projection.
        // For a pure continuous test, you may need to expose the raw dequantize kernel.
        
        let calculated = BoxCoxDequantizer::dequantize_scalar(ref_point.y, 8.0, ref_point.lambda);
        let error = (calculated - ref_point.exact_x).abs();
        
        assert!(
            error < epsilon,
            "Box-Cox mismatch at y={}, lambda={}: expected {}, got {} (error: {})",
            ref_point.y, ref_point.lambda, ref_point.exact_x, calculated, error
        );
    }
}

#[test]
fn test_mamba2_moe_recurrence_drift() {
    let golden = load_golden_vectors();
    
    // To proceed with Stage 1, this block will instantiate the updated `InferenceRunner`
    // and feed it the exact parameter matrices generated by the SymPy script.
    
    /*
    let mut runner = InferenceRunner::new_with_synthetic_weights(...);
    
    for (t, expected_step) in golden.trace.iter().enumerate() {
        let condition_vector = generate_synthetic_condition_for_step(t);
        let (w, x, y, z) = runner.step(&condition_vector);
        
        // Assert FOA output divergence is below the perceptual audio threshold
        assert!((w - expected_step.foa.w).abs() < 1e-3, "W channel drift at step {}", t);
        assert!((x - expected_step.foa.x).abs() < 1e-3, "X channel drift at step {}", t);
        assert!((y - expected_step.foa.y).abs() < 1e-3, "Y channel drift at step {}", t);
        assert!((z - expected_step.foa.z).abs() < 1e-3, "Z channel drift at step {}", t);
        
        // Assert router logic matches
        assert_eq!(runner.active_expert_indices, expected_step.top_2_experts);
    }
    */
}
