[package]
name = "web"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "WebAssembly client and WebRunner entrypoint"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["Document", "Window", "HtmlCanvasElement", "Element", "Blob", "BlobPropertyBag", "Url", "HtmlAnchorElement", "HtmlDocument", "Location", "AudioContext", "AudioContextOptions", "AudioBuffer", "AudioBufferSourceNode", "AudioDestinationNode", "AudioNode", "GainNode", "ScriptProcessorNode", "AudioProcessingEvent"] }
console_error_panic_hook = { workspace = true }
tracing-web = { workspace = true }
tracing = { workspace = true }
app = { workspace = true }
shared = { workspace = true }
inference = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = ["accesskit", "persistence", "wgpu"]
accesskit = ["app/accesskit", "eframe/accesskit"]
persistence = ["app/persistence", "eframe/persistence"]
wgpu = ["app/wgpu", "eframe/wgpu"]
glow = ["app/glow", "eframe/glow"]

